name: Run E2E Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: 9.0.304
  DOTNET_MAJOR: "9.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Install browsers
        run: pwsh PlaywrightTests/bin/Debug/net${{ env.DOTNET_MAJOR }}/playwright.ps1 install

      - name: Run tests
        env:
          DEVICE: "Desktop Chrome"
        run: dotnet test

      - name: Check traces directory
        if: always()
        run: ls -la PlaywrightTests/bin/Debug/net9.0/playwright-traces/

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-traces
          path: PlaywrightTests/bin/Debug/net9.0/playwright-traces/
          compression-level: 0
